---
version: '2.2'

services:
  db:
    image: postgres:10.6
    container_name: postgres_db
    command: -c fsync=off -c full_page_writes=off
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 60

  web:
    build: ""
    image: igivanov1728/python-db-image:1.8
    mem_limit: 200M
    environment:
      FLASK_ENV: development
      DB_NAME: test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
